jobs:
  - type: Artist
    area: 
      - Freelance
      - Higher Education
    grad_program:
      - Art & Architectural History #2 people
      - Anthropology
      - Music, Composition #3 people
  
  - type: Communications Staff
    area: Higher Education
    grad_program: Music, Critical Studies in Music and Sound

  - type: Audio Engineer
    area: Journalism
    grad_program: Music, Composition
    
  - type: Consultant 
    area: 
      - Consulting Firm
      - Freelance
      - Non-profit
    grad_program: 
      - English # 2 people
      - Sociology
  
  - type: Data Researcher
    area: 
      - Freelance
      - Higher Education
      - Non-profit
    grad_program: 
      - Art & Architectural History #2
      - Constructed Environment

  - type: Designer
    area: 
      - Freelance
      - Higher Education
    grad_program: 
      - Art & Architectural History
      - History
      - Music

  - type: Developer
    area: 
      - Freelance
      - Higher Education
      - Tech Industry
    grad_program:
      - English
      - History
      - Music

  - type: Educator
    area: 
      - Freelance
      - Higher Education
      - K12 Education
    grad_program:
      - Art & Architectural History #2
      - English #3 people
      - History

  - type: Event Staff
    area: Entertainment Industry
    grad_program:
      - Slavic Languages and Literatures
  - type: Full-time Parent
    grad_program: 
      - English
      - History

  - type: Lawyer
    area: 
      - Law Firm
      - Non-profit
    grad_program: 
      - English #2 people

  - type: Lecturer Faculty
    area: Higher Education
    grad_program:
      - Art & Architectural History
      - English #5 people
      - French
      - History #4 people

  - type: Library Staff
    area: 
      - Higher Education
      - Non-profit
    grad_program: 
      - English 
      - History #4
      - Music, Critical Studies in Music and Sound
  
  - type: Life Coach
    area: Freelance
    grad_program: Sociology

  - type: Management Staff
    area: 
      - Higher Education
      - Journalism
      - Marketing
    grad_program: 
      - Anthropology
      - Art & Architectural History #2
      - English #3
      - History #3
      - Music, Critical Studies in Music and Sound

  - type: Museum Staff
    area: 
      - Higher Education
      - Galleries and Museums
    grad_program: 
      - Anthropology
      - Art & Architectural History
      - Music, Critical Studies in Music and Sound 

  - type: Novice
    area: Religious Service
    grad_program: Spanish
  
  - type: Policy Analyst
    area: Non-profit
    grad_program: 
      - History
  
  - type: Research Specialist 
    area: 
      - Finance
      - Higher Education
      - Marketing
      - Non-profit
      - Tech Industry
    grad_program: 
      - Art & Architectural History
      - English #2
      - Music, Critical Studies in Music and Sound
      - Religious Studies
      - Spanish
  
  - type: Technical Writer
    area: Tech Industry
    grad_program: Art & Architectural History

  - type: Tenured Faculty
    area: Highed Education
    grad_program: 
      - Anthropology #3
      - Art & Architectural History #2
      - English #5
      - French
      - History #9
      - Philosophy
      - Sociology
      - Slavic Languages and Literatures
      - Spanish #2
  
  - type: writer
    area: Freelance
    grad_program: 
      - English #2