jobs:
  - type: Artist
    industry: 
      - Freelance
      - Higher Education
    uva_program:
      - Art & Architectural History #2 people
      - Anthropology
      - Music, Composition #3 people
  
  - type: Communications Staff
    industry: Higher Education
    uva_program: Music, Critical Studies in Music and Sound

  - type: Audio Engineer
    industry: Journalism
    uva_program: Music, Composition
    
  - type: Consultant 
    industry: 
      - Consulting Firm
      - Freelance
      - Non-profit
    uva_program: 
      - English # 2 people
      - Sociology
  
  - type: Data Researcher
    industry: 
      - Freelance
      - Higher Education
      - Non-profit
    uva_program: 
      - Art & Architectural History #2
      - Constructed Environment

  - type: Designer
    industry: 
      - Freelance
      - Higher Education
    uva_program: 
      - Art & Architectural History
      - History
      - Music

  - type: Developer
    industry: 
      - Freelance
      - Higher Education
      - Tech Industry
    uva_program:
      - English
      - History
      - Music

  - type: Educator
    industry: 
      - Freelance
      - Higher Education
      - K12 Education
    uva_program:
      - Art & Architectural History #2
      - English #3 people
      - History

  - type: Event Staff
    industry: Entertainment Industry
    uva_program:
      - Slavic Languages and Literatures
  - type: Full-time Parent
    uva_program: 
      - English
      - History

  - type: Lawyer
    industry: 
      - Law Firm
      - Non-profit
    uva_program: 
      - English #2 people

  - type: Lecturer Faculty
    industry: Higher Education
    uva_program:
      - Art & Architectural History
      - English #5 people
      - French
      - History #4 people

  - type: Library Staff
    industry: 
      - Higher Education
      - Non-profit
    uva_program: 
      - English 
      - History #4
      - Music, Critical Studies in Music and Sound
  
  - type: Life Coach
    industry: Freelance
    uva_program: Sociology

  - type: Management Staff
    industry: 
      - Higher Education
      - Journalism
      - Marketing
    uva_program: 
      - Anthropology
      - Art & Architectural History #2
      - English #3
      - History #3
      - Music, Critical Studies in Music and Sound

  - type: Museum Staff
    industry: 
      - Higher Education
      - Galleries and Museums
    uva_program: 
      - Anthropology
      - Art & Architectural History
      - Music, Critical Studies in Music and Sound 

  - type: Novice
    industry: Religious Service
    uva_program: Spanish
  
  - type: Policy Analyst
    industry: Non-profit
    uva_program: 
      - History
  
  - type: Research Specialist 
    industry: 
      - Finance
      - Higher Education
      - Marketing
      - Non-profit
      - Tech Industry
    uva_program: 
      - Art & Architectural History
      - English #2
      - Music, Critical Studies in Music and Sound
      - Religious Studies
      - Spanish
  
  - type: Technical Writer
    industry: Tech Industry
    uva_program: Art & Architectural History

  - type: Tenured Faculty
    industry: Highed Education
    uva_program: 
      - Anthropology #3
      - Art & Architectural History #2
      - English #5
      - French
      - History #9
      - Philosophy
      - Sociology
      - Slavic Languages and Literatures
      - Spanish #2
  
  - type: writer
    industry: Freelance
    uva_program: 
      - English #2